PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hs: <http://www.semanticweb.org/petros/ontologies/2020/0/untitled-ontology-9#>
PREFIX foaf: <http://xmlns.com/foaf/spec/>

SELECT ?spell ?cost ?type ?text 

WHERE{ ?spell rdf:type hs:Spell.
?spell hs:cost ?cost;
hs:spell_text ?text.
FILTER (?cost < 4)
OPTIONAL {?spell hs:has_spell_type ?type}

}
ORDER BY ?cost