PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hs: <http://www.semanticweb.org/petros/ontologies/2020/0/untitled-ontology-9#>

SELECT ?card ?hero ?cost

WHERE{
{
?card rdf:type hs:Priest_Card;
hs:cost ?cost;
hs:of_hero ?hero.
}
UNION
{
?card rdf:type hs:Warrior_Card;
hs:cost ?cost;
hs:of_hero ?hero.
}
}
ORDER BY ?cost