PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX hs: <http://www.semanticweb.org/petros/ontologies/2020/0/untitled-ontology-9#>
PREFIX foaf: <http://xmlns.com/foaf/spec/>

SELECT  DISTINCT ?card

WHERE{ ?deck rdf:type hs:Deck.
?deck hs:includes ?card
}