#1
SELECT "BASE".NAME, "BASE".CITY, "BASE".STATE, "BASE".STARS
FROM "USER03.YELP_BUSINESS2" 
WHERE "BASE".ISOPEN='1'
LIMIT 1000;
#2
SELECT "BASE".NAME, "BASE".ADDRESS, "BASE".CITY, "BASE".REVIEWCOUNT
FROM "USER03.YELP_BUSINESS2"
WHERE "BASE".CATEGORIES='Drugstores'
ORDER BY TO_NUMBER("BASE".REVIEWCOUNT) DESC;
#3
SELECT "BASE".CATEGORIES, SUM(TO_NUMBER("BASE".REVIEWCOUNT)) AS SUM FROM "USER03.YELP_BUSINESS2"
WHERE "BASE".ISOPEN='1'
AND "ATTRIBUTES".OPEN24HOURS = 'True'
GROUP BY "BASE".CATEGORIES;

#4
SELECT "BASE".STATE, COUNT(*) AS BUSINESS_COUNT FROM "USER03.YELP_BUSINESS2"
WHERE "ATTRIBUTES".SMOKING='False'
AND "HOURS".SUNDAY!='NONE'
GROUP BY "BASE".STATE;

#5
SELECT "PERHOUR".WEEKDAY, "PERHOUR".HOUR, SUM("PERHOUR".CHECKINS) AS CHEKIN_SUM FROM "USER03.YELP_CHECKIN6"
GROUP BY "PERHOUR".WEEKDAY, "PERHOUR".HOUR;

#6
SELECT "BASE".CATEGORIES, SUM(TO_NUMBER("PERHOUR".CHECKINS)) AS CHEKIN_SUM
FROM "USER03.YELP_BUSINESS3" INNER JOIN "USER03.YELP_CHECKIN5"
ON  "USER03.YELP_BUSINESS3".PK = "USER03.YELP_CHECKIN5"."PERHOUR".BUSINESSID
WHERE ("PERHOUR".HOUR = '14:00'
OR "PERHOUR".HOUR = '15:00'
OR "PERHOUR".HOUR = '16:00')
AND "PERHOUR".WEEKDAY!='Sat'
AND "PERHOUR".WEEKDAY!='Sun'
AND "BASE".ISOPEN='1'
GROUP BY "BASE".CATEGORIES;

#7
SELECT /*+ USE_SORT_MERGE_JOIN*/ "BASE".NAME, "BASE".NEIGHBORHOOD, "BASE".ADDRESS, "BASE".CITY, "BASE".STATE, "BASE".POSTALCODE, "BASE".LATITUDE, "BASE".LONGITUDE, "BASE".STARS, "BASE".REVIEWCOUNT, "BASE".ISOPEN, "BASE".CATEGORIES, SUM(TO_NUMBER("PERHOUR".CHECKINS)) AS CHEKIN_SUM
FROM "USER03.YELP_BUSINESS2" INNER JOIN "USER03.YELP_CHECKIN5"
ON  "USER03.YELP_BUSINESS2".PK = "USER03.YELP_CHECKIN5"."PERHOUR".BUSINESSID
WHERE "PERHOUR".WEEKDAY='Sat'
GROUP BY "BASE".NAME, "BASE".NEIGHBORHOOD, "BASE".ADDRESS, "BASE".CITY, "BASE".STATE, "BASE".POSTALCODE, "BASE".LATITUDE, "BASE".LONGITUDE, "BASE".STARS, "BASE".REVIEWCOUNT, "BASE".ISOPEN, "BASE".CATEGORIES
ORDER BY SUM(TO_NUMBER("PERHOUR".CHECKINS)) DESC
LIMIT 100;

